# Generated by Django 2.0 on 2017-12-09 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_auto_20171209_0901'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grdes',
            new_name='Grades',
        ),
    ]
