# Generated by Django 2.0 on 2017-12-09 02:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_auto_20171209_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='semester date'),
            preserve_default=False,
        ),
    ]
