# Generated by Django 2.0 on 2017-12-10 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_auto_20171209_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('course_id', models.CharField(max_length=20)),
                ('credit', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='grade',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='none', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='class_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
        migrations.AddField(
            model_name='sc',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.Student'),
        ),
    ]
