# Generated by Django 2.0 on 2017-12-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0008_auto_20171210_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sc',
            name='course',
        ),
        migrations.AddField(
            model_name='sc',
            name='course',
            field=models.ManyToManyField(to='grades.Course'),
        ),
        migrations.RemoveField(
            model_name='sc',
            name='student',
        ),
        migrations.AddField(
            model_name='sc',
            name='student',
            field=models.ManyToManyField(to='grades.Student'),
        ),
    ]
